### ISSUE TITLE
jQuery, C#

### ISSUE THREAD

**Issue by Moonfizzle** [OpenFIGI/api-examples#2]

**Comment by jeandelcapitaine** [comment]
Also pure JavaScript.

Thanks

**Comment by jayflo** [comment]
@Moonfizzle since the API is not CORS enabled, any request you make to the API will need to be sent through your website's backend.

@jeandelcapitaine there is a pure node.js example already https://github.com/OpenFIGI/api-examples/blob/master/node7.9.js which does not use any npm packages.  Do you mean JS that runs in the browser?  We can provide this example also, but please notice my CORS remark above.

**Comment by jeandelcapitaine** [comment]
Hi,

Yes indeed, I was interested in a functional JS through my browser. I ran
into same-origin-policy issue while writing the script, and I thought you
may have had a solution for this.

Beat Regards,

Jean

**Comment by jayflo** [comment]
Jean, currently there is no plan to enable CORS for the API so you must route any request through your own server(s).  That being said, let us know if there are other languages you are interested in.

**Comment by jayflo** [comment]
C# example added by @achvaicer

**Comment by jayflo** [comment]
Closing issue since API is not CORS enabled and any browser request to the API must be routed through the application's backend server.  Will notify if this ever changes and provide a browser example at that time.
