### ISSUE TITLE
Multiple Figis for same security

### ISSUE THREAD

**Issue by algoRory** [OpenFIGI/api-examples#22]
Your API is good but the data is not that reliable - Figi is meant to be unique, however, I have found quite a few securities that have two figis - For example
figi: BBG000CX7XG6
figi: BBG000CX7XX7
These are linked to the same exact security - how can we tell from the API result which is the correct figi to use

**Comment by jayflo** [comment]
@algoRory Thank you for the question.  See this post:

https://openfigi.com/about/news/2018/6/15/figi-equity-levels-of-assignment-english

This particular situation is not due to unreliable data, but is by design for Equities.  BBG000CX7XG6 is a composite FIGI, while BBG000CX7XX7 is the exchange/venue FIGI.  You can see this on openfigi.com/search:

https://openfigi.com/search#!?simpleSearchString=BBG000CX7XG6&page=1

---

For data related questions, consider going straight to the source by submitting feedback through the website:

https://openfigi.com/feedback

That team will be able to answer all of your questions.  Certainly feel free to ask questions here as well, but it is primarily developers monitoring these issues and we'll generally rely on that team for data questions.

**Comment by algoRory** [comment]
Ok that actually makes sense - so in theory, when I see the Figi and CompositeID as being the ID this indicates that this is the primary Figi for the composite Group?

**Comment by jayflo** [comment]
Hopefully I'm interpreting the question correctly, but yes, when you see the composite figi and the figi are the same, you know the FIGI is a composite.  There are some exceptions when there may not be a composite or exchange level figi.

**Comment by algoRory** [comment]
Yes the reason for the question was to work out what to do when receiving more than one figi for the same ISIN/MIC/CURRENCY group - Our static data is stored with a unique key using this unique group and I was using figi as the unique identifier for database storage.  I have now updated my code so that when more than one figi is mapped it will use the figi where figi=compositeid. thanks for your help

**Comment by jayflo** [comment]
@algoRory It's possible there was some misinterpretation, or misunderstanding in the conversation with the OpenFIGI data team.  So that there are not competing sources of information, I will defer to them.  I believe they are working on a response for you.

**Comment by mmiller678** [comment]
What was the final response to this question as I am seeing the same issue?

**Comment by algoRory** [comment]
The answer depends on how you are using the data - I can only explain from the perspective that I am using the data for. We maintain one key security as the primary composite ID. This is generally where the FIGI is equal to the Composite ID.  For example FIGI: BBG000BCCRV3 and CompositeID: BBG000BCCRV3 - We use this security as the primary Security for all securities with the CompositeID=BBG000BCCRV3.

This works for all securities where the 2 digit Bloomberg Exchange Code is NOT equal to the Bloomberg Composite Country Code (in the above example GR=Germany). 

When the 2 digit country code is equal to the 2 digit exchange code (Example SS for Sweden and SS for NASDAQ OMX NORDIC) I was told that there is a known bug and you will not find a security that has the FIGI and CompositeID as being equal. In this instance, we simply store all securities for the same compositeID and create one more that adds a security with a figi=CompositeID to maintain a standardized structure within our own database.

**Comment by algoRory** [comment]
in my opinion, having data consistency makes it far easier for people to follow and build tools that are useful (without too much coding to deal with nuances). So having some securities that have a special composite row in your data store as opposed to others that do not is what I would call a bug or poor structure. 

Why would you put these rows in for some and not others? Having one security per Composite group as the primary composite ID makes complete sense as it follows the trading convention where you can group regulatory field such a BBO for the country. What I found is that those that did not have a row like this were typically due to the fact that there is only one listing in the country.

**Comment by jayflo** [comment]
I'm guessing that FIGIs have been assigned this way historically, and it is involves factors around whether the composite is necessary (in the sense of financial instruments) as a FIGI.  For instance, in the case of countries with only a single exchange, any country level information would be (?) equivalent to the exchange level information. 

In any case, I am no expert on the data.  From a pure identification point of view, I agree that consistency would be easier to work with.

I'll close for now since the question is answered.  Who knows, perhaps in the future the consistency will take priority over  financial instrument relevance.
