### ISSUE TITLE
Non-matured securities

### ISSUE THREAD

**Issue by mdebrauw** [OpenFIGI/api-examples#29]
Hi,

I am trying to pull in mapping data for `Govt` bonds that have not matured:

```
{
    'idType': 'BASE_TICKER',
    'idValue': 'DGB',
    'securityType2': 'Govt',
    'maturity': ['2019-11-22', null]
}
```

As described in the documentation, this only gives me bonds with a maturity between 2019-11-22 and 2020-11-22.

Two questions I have:   
1. Has it been considered to treat the `maturity` array as an "after/before pair", so it is easy to get all un-matured bonds for a `BASE_TICKER` as-of a certain date if before is left `null`?
2. What would be the best way to go about this? I was thinking: create a loop for a certain amount  (50?) of years in the future and issue multiple API requests for each subsequent year.

Thanks!

**Comment by jayflo** [comment]
> Has it been considered to treat the maturity array as an "after/before pair", so it is easy to get all un-matured bonds for a BASE_TICKER as-of a certain date if before is left null?

Not sure I completely understand (probably because I don't understand bonds well enough).  Right now the request will return you all DGB bonds with a maturity after 2019-11-22 (i.e. all un-matured DGB bonds as of 2019-11-22).  How does this differ from what you're asking?

**Comment by mdebrauw** [comment]
Hi, thanks for your reply! Apologies, I should have added an example.

If I issue this mapping request:
```
{
    'idType': 'BASE_TICKER',
    'idValue': 'DGB',
    'securityType2': 'Govt',
    'maturity': ['2019-11-22', null]
}
```

It returns these two bonds:
```
BBG007Z62S80;KINGDOM OF DENMARK DGB 0 1/4 11/15/20;DGB 0.25 11/15/20
BBG00GLY3CR7;KINGDOM OF DENMARK DGB 0 1/4 11/15/20;DGB 0.25 11/15/20 3Y
```

This is because the maturity date (11/15/20) is within 1 year from 2019-11-22. This is documented behaviour (see https://www.openfigi.com/api).

To get bonds with ticker DBG maturing in more than 1 year's time I would need to issue subsequent requests, for example (notice the changed maturity date):

```
{
    'idType': 'BASE_TICKER',
    'idValue': 'DGB',
    'securityType2': 'Govt',
    'maturity': ['2020-11-22', null]
}
```

will return:

```
BBG001CX88S5;KINGDOM OF DENMARK DGB 3 11/15/21;DGB 3 11/15/21;COEI5292749
```

Etc. 

The web ui does allow me to put in a start maturity date and will give all bonds with a maturity date after that (for example: https://www.openfigi.com/search#!?page=1&simpleSearchString=DGB&marketSector=Govt&facets=maturity:..%5B2019-11-26T00:00:00Z%20TO%20*%5D)

**Comment by jayflo** [comment]
Ah.  I see what you're saying.  Yes, in the API /mapping request, if you don't pass the start/end date, then we automatically fill in the date so you're capped at 1 year of results.  On the web search you're capped by the paging (so you may need multiple requests to get the entire result set).

The reason we did this on the API /mapping request is because we return the entire result set, and we've had problems in the past with large result sets.  For example, if you use TICKER or BASE_TICKER for equities, the results can be tens to hundreds of thousands of FIGIs.

Right now, if you're using BASE_TICKER+Govt, I don't believe maturity is even required.  So you could just all DGB bonds and then filter them on your side.

But also, in the cases where maturity/expiration are not required, we can likely remove the 1 year cap.  I will create a work item on our side to discuss with the openfigi team.

**Comment by jayflo** [comment]
@mdebrauw Give this a try now.  In cases when `maturity` and `expiration` are not required, it should no longer restrict open ended range queries to 1 year.  Please let me know if you have any problems.

**Comment by jayflo** [comment]
Closing.  Again, please let me know if you encounter any issues.

**Comment by mdebrauw** [comment]
@jayflo Excellent, works like a charm! Thank you very much.
