### ISSUE TITLE
Unable to send multiple types of the same parameter to /v2/search and /v2/filter

### ISSUE THREAD

**Issue by nghtstr** [OpenFIGI/api-examples#41]
Ok, so here is the sample code that I am working with:

```
curl --location --request POST 'https://api.openfigi.com/v2/search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "ibm",
    "exchCode":"US",
    "securityType": "Common Stock"
}'
```

I would like to be able to search for multiple security types with a single API call. Such as:

```
curl --location --request POST 'https://api.openfigi.com/v2/search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "ibm",
    "exchCode":"US",
    "securityType": ["Common Stock","Mutual Fund"]
}'
```

Or even across multiple `exchCode`s, like something like this:
```
curl --location --request POST 'https://api.openfigi.com/v2/search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "ibm",
    "exchCode":["CHICAGO", "NASDAQ", "NEW YORK", "NYSE AMERICAN", "OTC US", "OTC BB", "PINK SHEETS", "TORONTO", "US"],
    "securityType": ["Common Stock","Mutual Fund"]
}'
```

Right now, as I see it, I would have to do an API call for every iteration of `exchCode` and `securityType` and then combine the results, which could take a significant number of api calls. Is there some way to be able to do this as a single API call?

**Comment by ms82494** [comment]
From the documentation of the [mapping endpoint:](https://www.openfigi.com/api#post-v2-mapping) "The request should be an Array of Objects (or Mapping Jobs), e.g. [{...}, {...}, ...], where each Object has the following properties:..."

So, you only need one API call, but you provide a list of query jobs. Something like this will work:
```
curl 'https://api.openfigi.com/v2/mapping' \
    --request POST \
    --header 'Content-Type: application/json' \
    --data '[{"idType": "BASE_TICKER","idValue": "IBM", "securityType2": "Common Stock", "exchCode": "NEW YORK"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Preferred Stock"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Corp", "exchCode": "NEW YORK"}]'
```

**Comment by ms82494** [comment]
I think for your purposes the `mapping` endpoint is preferable to `search`. From its [documentation](https://www.openfigi.com/api#post-v2-mapping): 'The request should be an Array of Objects (or Mapping Jobs), e.g. [{...}, {...}, ...], where each Object has the following properties:..."

Your syntax is not far off, but instead of enumerating elements (e.g. `["Common Stock","Mutual Fund"]`), you enumerate entire queries/jobs, that are then executed in a single API call. Something like this will work:
```
curl 'https://api.openfigi.com/v2/mapping' \
    --request POST \
    --header 'Content-Type: application/json' \
    --header 'X-OPENFIGI-APIKEY: c55a1b6c-72ef-4531-9e56-c4e5393bdc49' \
    --data '[{"idType": "BASE_TICKER","idValue": "IBM", "securityType2": "Common Stock", "exchCode": "NEW YORK"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Preferred Stock"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Corp", "exchCode": "NEW YORK"}]'
```

**Comment by ms82494** [comment]
I think for your purposes the mapping endpoint is preferable to search. From its documentation: 'The request should be an Array of Objects (or Mapping Jobs), e.g. [{...}, {...}, ...], where each Object has the following properties:..."

Your syntax is not far off, but instead of enumerating elements (e.g. ["Common Stock","Mutual Fund"]), you enumerate entire queries/jobs, that are then executed in a single API call. Something like this will work:

curl 'https://api.openfigi.com/v2/mapping' \
    --request POST \
    --header 'Content-Type: application/json' \
    --data '[{"idType": "BASE_TICKER","idValue": "IBM", "securityType2": "Common Stock", "exchCode": "NEW YORK"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Preferred Stock"},
        {"idType":"BASE_TICKER", "idValue": "IBM", "securityType2":"Corp", "exchCode": "NEW YORK"}]'
